services:
  redpanda:
    image: redpandadata/redpanda:latest
    command:
      - redpanda
      - start
      - --smp
      - '1'
      - --memory
      - '1G'
      - --overprovisioned
      - --node-id
      - '0'
      - --kafka-addr
      - PLAINTEXT://0.0.0.0:9092,OUTSIDE://0.0.0.0:19092
      - --advertise-kafka-addr
      - PLAINTEXT://redpanda:9092,OUTSIDE://localhost:19092
    ports:
      - "9092:9092"
      - "19092:19092"
    healthcheck:
      test: ["CMD", "rpk", "cluster", "health"]
      interval: 5s
      timeout: 5s
      retries: 10

  producer:
    build: .
    command: python3 producer.py
    environment:
      KAFKA_BOOTSTRAP: redpanda:9092
    depends_on:
      redpanda:
        condition: service_healthy

  consumer:
    build: .
    command: python3 consumer.py
    environment:
      KAFKA_BOOTSTRAP: redpanda:9092
      POSTGRES_HOST: aws-0-ap-southeast-1.pooler.supabase.com
      POSTGRES_PORT: 5432
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres.foccwfvqteqqdzuyvwcl
      POSTGRES_PASSWORD: Kr$$naalmightygod
    depends_on:
      redpanda:
        condition: service_healthy